// <auto-generated />
using System;
using Cims.WorkflowLib.Example01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WorkflowLib.Example01.Migrations
{
    [DbContext(typeof(DeliveringContext))]
    [Migration("20231221150425_AddProductTransfer")]
    partial class AddProductTransfer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditonalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CloseOrderDt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyUid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CouldBeCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerUid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenOrderDt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProductsPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("DeliveryOperationId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.InitialOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("InitialOrders");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVatRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ShippingAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyText")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Delivery.DeliveryMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmployDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICQ")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplacementMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HeadItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HeadItemId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HardDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationItems");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenDt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrganizationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationItemId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreationAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroupByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("CreationAuthorId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Monetary.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payer")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receiver")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActualExecutionTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EstimatedExecutionTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutorIsEmulationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutorReplacedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExpiredNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActualExecutionTimeId");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("EstimatedExecutionTimeId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("ExecutorIsEmulationId");

                    b.HasIndex("ExecutorReplacedId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("BusinessTasks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BusinessTask");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.DeliveryOrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("DeliveryOrderProducts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IngredientProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinalProductId");

                    b.HasIndex("IngredientProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.InitialOrderIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryWh2KitchenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InitialOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryWh2KitchenId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("InitialOrderId");

                    b.ToTable("InitialOrderIngredient");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.InitialOrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryKitchen2WhId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryWh2KitchenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InitialOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryKitchen2WhId");

                    b.HasIndex("DeliveryWh2KitchenId");

                    b.HasIndex("InitialOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("InitialOrderProducts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProductTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("NewQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("NewStatus")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OldQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("OldStatus")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OrderProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WHProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("WHProductId");

                    b.ToTable("ProductTransfers");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuaranteePeriodInMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProjectPhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPhase");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPlanItem");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.WHProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WHProducts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Risk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreationAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvingAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvingComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResolvingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("CreationAuthorId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResolvingAuthorId");

                    b.ToTable("Risk");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreationAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("CreationAuthorId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Performance.ExecutionTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeBegin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExecutionTime");
                });

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerCompaniesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "CustomerCompaniesId");

                    b.HasIndex("CustomerCompaniesId");

                    b.ToTable("CompanyContract");
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.Property<long>("CompaniesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompaniesId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("CompanyEmployee");
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("ContractCustomer");
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OurEmployeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "OurEmployeesId");

                    b.HasIndex("OurEmployeesId");

                    b.ToTable("ContractEmployee");
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OurOrganizationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "OurOrganizationsId");

                    b.HasIndex("OurOrganizationsId");

                    b.ToTable("ContractOrganization");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Delivery.DeliveryOperation", b =>
                {
                    b.HasBaseType("Cims.WorkflowLib.Models.Business.Processes.BusinessTask");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ContactId");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.HasDiscriminator().HasValue("DeliveryOperation");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Example01.Models.DeliveryKitchen2Wh", b =>
                {
                    b.HasBaseType("Cims.WorkflowLib.Models.Business.Delivery.DeliveryOperation");

                    b.Property<string>("GeneratedOrderQrCode")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DeliveryKitchen2Wh");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Example01.Models.DeliveryWh2Kitchen", b =>
                {
                    b.HasBaseType("Cims.WorkflowLib.Models.Business.Delivery.DeliveryOperation");

                    b.HasDiscriminator().HasValue("DeliveryWh2Kitchen");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Delivery.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Delivery.DeliveryOperation", "DeliveryOperation")
                        .WithMany()
                        .HasForeignKey("DeliveryOperationId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.Navigation("DeliveryMethod");

                    b.Navigation("DeliveryOperation");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.InitialOrder", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId");

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.Navigation("Address");

                    b.Navigation("Contact");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Customer", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Organization", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", "HeadItem")
                        .WithMany()
                        .HasForeignKey("HeadItemId");

                    b.Navigation("Company");

                    b.Navigation("HeadItem");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", "ParentItem")
                        .WithMany("SubItems")
                        .HasForeignKey("ParentItemId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Address");

                    b.Navigation("ParentItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Skill", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany("UserAccounts")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationItemId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserGroup", null)
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "CreationAuthor")
                        .WithMany()
                        .HasForeignKey("CreationAuthorId");

                    b.Navigation("ChangeAuthor");

                    b.Navigation("CreationAuthor");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Monetary.Payment", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", null)
                        .WithMany("Payments")
                        .HasForeignKey("DeliveryOrderId");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Performance.ExecutionTime", "ActualExecutionTime")
                        .WithMany()
                        .HasForeignKey("ActualExecutionTimeId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", null)
                        .WithMany("PreparingOperations")
                        .HasForeignKey("DeliveryOrderId");

                    b.HasOne("Cims.WorkflowLib.Models.Performance.ExecutionTime", "EstimatedExecutionTime")
                        .WithMany()
                        .HasForeignKey("EstimatedExecutionTimeId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "ExecutorIsEmulation")
                        .WithMany()
                        .HasForeignKey("ExecutorIsEmulationId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "ExecutorReplaced")
                        .WithMany()
                        .HasForeignKey("ExecutorReplacedId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId");

                    b.Navigation("ActualExecutionTime");

                    b.Navigation("EstimatedExecutionTime");

                    b.Navigation("Executor");

                    b.Navigation("ExecutorIsEmulation");

                    b.Navigation("ExecutorReplaced");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.DeliveryOrderProduct", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("DeliveryOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Ingredient", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "FinalProduct")
                        .WithMany()
                        .HasForeignKey("FinalProductId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "IngredientProduct")
                        .WithMany()
                        .HasForeignKey("IngredientProductId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.Navigation("FinalProduct");

                    b.Navigation("IngredientProduct");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.InitialOrderIngredient", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Example01.Models.DeliveryWh2Kitchen", null)
                        .WithMany("InitialOrderIngredients")
                        .HasForeignKey("DeliveryWh2KitchenId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.InitialOrder", "InitialOrder")
                        .WithMany()
                        .HasForeignKey("InitialOrderId");

                    b.Navigation("Ingredient");

                    b.Navigation("InitialOrder");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.InitialOrderProduct", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Example01.Models.DeliveryKitchen2Wh", null)
                        .WithMany("InitialOrderProducts")
                        .HasForeignKey("DeliveryKitchen2WhId");

                    b.HasOne("Cims.WorkflowLib.Example01.Models.DeliveryWh2Kitchen", null)
                        .WithMany("InitialOrderProducts")
                        .HasForeignKey("DeliveryWh2KitchenId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.InitialOrder", "InitialOrder")
                        .WithMany()
                        .HasForeignKey("InitialOrderId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("InitialOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Product", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProductTransfer", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.ProductTransfer", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.WHProduct", "WHProduct")
                        .WithMany()
                        .HasForeignKey("WHProductId");

                    b.Navigation("Parent");

                    b.Navigation("WHProduct");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Company");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProjectPhase", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Project", "Project")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.ProjectPlanItem", "ProjectPlanItem")
                        .WithMany()
                        .HasForeignKey("ProjectPlanItemId");

                    b.Navigation("Project");

                    b.Navigation("ProjectPlanItem");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.ProjectPlanItem", null)
                        .WithMany("Items")
                        .HasForeignKey("ProjectPlanItemId");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Recipe", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.WHProduct", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Risk", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Risks")
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", "CreationAuthor")
                        .WithMany()
                        .HasForeignKey("CreationAuthorId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Products.Project", null)
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", "ResolvingAuthor")
                        .WithMany()
                        .HasForeignKey("ResolvingAuthorId");

                    b.Navigation("ChangeAuthor");

                    b.Navigation("CreationAuthor");

                    b.Navigation("ResolvingAuthor");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Comments")
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.UserAccount", "CreationAuthor")
                        .WithMany()
                        .HasForeignKey("CreationAuthorId");

                    b.Navigation("CreationAuthor");
                });

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CustomerCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("OurEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cims.WorkflowLib.Models.Business.InformationSystem.Organization", null)
                        .WithMany()
                        .HasForeignKey("OurOrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Delivery.DeliveryOperation", b =>
                {
                    b.HasOne("Cims.WorkflowLib.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Delivery.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Cims.WorkflowLib.Models.Business.Address", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.Navigation("Contact");

                    b.Navigation("DeliveryMethod");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.BusinessDocuments.DeliveryOrder", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PreparingOperations");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Navigation("SubItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Navigation("ChildTasks");

                    b.Navigation("Comments");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.Navigation("ProjectPhases");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Models.Business.Products.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Example01.Models.DeliveryKitchen2Wh", b =>
                {
                    b.Navigation("InitialOrderProducts");
                });

            modelBuilder.Entity("Cims.WorkflowLib.Example01.Models.DeliveryWh2Kitchen", b =>
                {
                    b.Navigation("InitialOrderIngredients");

                    b.Navigation("InitialOrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
