// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowLib.Examples.Delivering.ServiceInteraction.BL.DbContexts;

#nullable disable

namespace WorkflowLib.Examples.Delivering.ServiceInteraction.BL.Migrations
{
    [DbContext(typeof(ServiceInteractionDbContext))]
    [Migration("20240503110950_UseDeliveryOrderIdInsteadOfExplicitType")]
    partial class UseDeliveryOrderIdInsteadOfExplicitType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerCompaniesId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractsId", "CustomerCompaniesId");

                    b.HasIndex("CustomerCompaniesId");

                    b.ToTable("CompanyContract");
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.Property<long>("CompaniesId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeesId")
                        .HasColumnType("bigint");

                    b.HasKey("CompaniesId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("CompanyEmployee");
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomersId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("ContractCustomer");
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("bigint");

                    b.Property<long>("OurEmployeesId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractsId", "OurEmployeesId");

                    b.HasIndex("OurEmployeesId");

                    b.ToTable("ContractEmployee");
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("bigint");

                    b.Property<long>("OurOrganizationsId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractsId", "OurOrganizationsId");

                    b.HasIndex("OurOrganizationsId");

                    b.ToTable("ContractOrganization");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.BusinessDocuments.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("integer");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasVatRegistration")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HomePhone")
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OfficeEmail")
                        .HasColumnType("text");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("integer");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AuthProviderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EmployDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICQ")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ReplacementMode")
                        .HasColumnType("integer");

                    b.Property<string>("Skype")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("HeadItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HeadItemId");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HardDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationItem");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSeenDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OrganizationItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationItemId");

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BDEConnector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("StartElementId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartElementId");

                    b.ToTable("BDEConnector");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BPStateEndpointCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long>("BusinessProcessStateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("EndpointCallId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessStateId");

                    b.HasIndex("EndpointCallId");

                    b.ToTable("BPStateEndpointCalls");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessDiagram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusinessDiagram");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessDiagramElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BusinessDiagramId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDiagramId");

                    b.ToTable("BusinessDiagramElement");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("DiagramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("ParentId");

                    b.ToTable("BusinessProcesses");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcessState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessProcessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.ToTable("BusinessProcessStates");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcessStateTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessProcessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("EndpointCallId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FromStateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PreviousId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ToStateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.HasIndex("EndpointCallId");

                    b.HasIndex("FromStateId");

                    b.HasIndex("PreviousId");

                    b.HasIndex("ToStateId");

                    b.ToTable("BusinessProcessStateTransitions");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualDateTimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDateTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessProcessStateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EstimatedDateTimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedDateTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExecutorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExecutorIsEmulationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExecutorReplacedId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ExpiredNotificationSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmulation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessStateId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("ExecutorIsEmulationId");

                    b.HasIndex("ExecutorReplacedId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("BusinessTasks");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualDateTimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDateTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long>("BusinessProcessId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EstimatedDateTimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedDateTimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("InitiatorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEmulation")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ParentInstanceId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowInstanceMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("WorkflowInstanceMember");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowTrackingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActiveTaskId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BDEConnectorId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTaskId");

                    b.HasIndex("BDEConnectorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowTrackingItems");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("CompletePercent")
                        .HasColumnType("integer");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuaranteePeriodInMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.ProjectPhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPhase");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPlanItem");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Risk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChangeAuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreationAuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResolvingAuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolvingComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ResolvingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("CreationAuthorId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResolvingAuthorId");

                    b.ToTable("Risk");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("integer");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreationAuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<long?>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("CreationAuthorId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("WorkflowLib.Models.Logging.DbgLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceDetails")
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("SourceStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DbgLogs");
                });

            modelBuilder.Entity("WorkflowLib.Models.Network.MicroserviceConfigurations.Endpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<int?>("EndpointDeploymentType")
                        .HasColumnType("integer");

                    b.Property<long?>("EndpointTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NetworkAddress")
                        .HasColumnType("text");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndpointTypeId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiMethodName")
                        .HasColumnType("text");

                    b.Property<int?>("AttemptsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("EndpointCallType")
                        .HasColumnType("integer");

                    b.Property<long?>("EndpointFromId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EndpointToId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EndpointTypeFromId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EndpointTypeToId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MessageBrokerType")
                        .HasColumnType("integer");

                    b.Property<string>("QueueName")
                        .HasColumnType("text");

                    b.Property<int?>("TimeoutLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EndpointFromId");

                    b.HasIndex("EndpointToId");

                    b.HasIndex("EndpointTypeFromId");

                    b.HasIndex("EndpointTypeToId");

                    b.ToTable("EndpointCalls");
                });

            modelBuilder.Entity("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EndpointTypes");
                });

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CustomerCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("OurEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Organization", null)
                        .WithMany()
                        .HasForeignKey("OurOrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Customer", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WorkflowLib.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Organization", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", "HeadItem")
                        .WithMany()
                        .HasForeignKey("HeadItemId");

                    b.Navigation("Company");

                    b.Navigation("HeadItem");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", "ParentItem")
                        .WithMany("SubItems")
                        .HasForeignKey("ParentItemId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParentItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Skill", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", null)
                        .WithMany("UserAccounts")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationItemId");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BDEConnector", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessDiagramElement", "StartElement")
                        .WithMany()
                        .HasForeignKey("StartElementId");

                    b.Navigation("StartElement");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BPStateEndpointCall", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcessState", "BusinessProcessState")
                        .WithMany()
                        .HasForeignKey("BusinessProcessStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointCall", "EndpointCall")
                        .WithMany()
                        .HasForeignKey("EndpointCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcessState");

                    b.Navigation("EndpointCall");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessDiagramElement", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessDiagram", null)
                        .WithMany("Elements")
                        .HasForeignKey("BusinessDiagramId");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessDiagram", "Diagram")
                        .WithMany()
                        .HasForeignKey("DiagramId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcess", "Parent")
                        .WithMany("SubProcesses")
                        .HasForeignKey("ParentId");

                    b.Navigation("Diagram");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcessState", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcess", "BusinessProcess")
                        .WithMany()
                        .HasForeignKey("BusinessProcessId");

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcessStateTransition", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcess", "BusinessProcess")
                        .WithMany()
                        .HasForeignKey("BusinessProcessId");

                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointCall", "EndpointCall")
                        .WithMany()
                        .HasForeignKey("EndpointCallId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcessState", "FromState")
                        .WithMany()
                        .HasForeignKey("FromStateId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcessStateTransition", "Previous")
                        .WithMany()
                        .HasForeignKey("PreviousId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcessState", "ToState")
                        .WithMany()
                        .HasForeignKey("ToStateId");

                    b.Navigation("BusinessProcess");

                    b.Navigation("EndpointCall");

                    b.Navigation("FromState");

                    b.Navigation("Previous");

                    b.Navigation("ToState");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcessState", "BusinessProcessState")
                        .WithMany()
                        .HasForeignKey("BusinessProcessStateId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "ExecutorIsEmulation")
                        .WithMany()
                        .HasForeignKey("ExecutorIsEmulationId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "ExecutorReplaced")
                        .WithMany()
                        .HasForeignKey("ExecutorReplacedId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessTask", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId");

                    b.Navigation("BusinessProcessState");

                    b.Navigation("Executor");

                    b.Navigation("ExecutorIsEmulation");

                    b.Navigation("ExecutorReplaced");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowInstance", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessProcess", "BusinessProcess")
                        .WithMany()
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.WorkflowInstance", "ParentInstance")
                        .WithMany()
                        .HasForeignKey("ParentInstanceId");

                    b.Navigation("BusinessProcess");

                    b.Navigation("Initiator");

                    b.Navigation("ParentInstance");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowInstanceMember", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessTask", "BusinessTask")
                        .WithMany()
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.WorkflowInstance", "Instance")
                        .WithMany("Members")
                        .HasForeignKey("InstanceId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("BusinessTask");

                    b.Navigation("Instance");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowTrackingItem", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessTask", "ActiveTask")
                        .WithMany()
                        .HasForeignKey("ActiveTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Processes.BDEConnector", "BDEConnector")
                        .WithMany()
                        .HasForeignKey("BDEConnectorId");

                    b.HasOne("WorkflowLib.Models.Business.SocialCommunication.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("WorkflowLib.Models.Business.Processes.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveTask");

                    b.Navigation("BDEConnector");

                    b.Navigation("Comment");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Customers.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.BusinessDocuments.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.ProjectPhase", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Products.Project", "Project")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("ProjectId");

                    b.HasOne("WorkflowLib.Models.Business.Products.ProjectPlanItem", "ProjectPlanItem")
                        .WithMany()
                        .HasForeignKey("ProjectPlanItemId");

                    b.Navigation("Project");

                    b.Navigation("ProjectPlanItem");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Products.ProjectPlanItem", null)
                        .WithMany("Items")
                        .HasForeignKey("ProjectPlanItemId");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Risk", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Risks")
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", "CreationAuthor")
                        .WithMany()
                        .HasForeignKey("CreationAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Products.Project", null)
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.Employee", "ResolvingAuthor")
                        .WithMany()
                        .HasForeignKey("ResolvingAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeAuthor");

                    b.Navigation("CreationAuthor");

                    b.Navigation("ResolvingAuthor");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.HasOne("WorkflowLib.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Comments")
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("WorkflowLib.Models.Business.InformationSystem.UserAccount", "CreationAuthor")
                        .WithMany()
                        .HasForeignKey("CreationAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Models.Business.Processes.WorkflowInstance", null)
                        .WithMany("Comments")
                        .HasForeignKey("WorkflowInstanceId");

                    b.Navigation("CreationAuthor");
                });

            modelBuilder.Entity("WorkflowLib.Models.Network.MicroserviceConfigurations.Endpoint", b =>
                {
                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointType", "EndpointType")
                        .WithMany()
                        .HasForeignKey("EndpointTypeId");

                    b.Navigation("EndpointType");
                });

            modelBuilder.Entity("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointCall", b =>
                {
                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.Endpoint", "EndpointFrom")
                        .WithMany()
                        .HasForeignKey("EndpointFromId");

                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.Endpoint", "EndpointTo")
                        .WithMany()
                        .HasForeignKey("EndpointToId");

                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointType", "EndpointTypeFrom")
                        .WithMany()
                        .HasForeignKey("EndpointTypeFromId");

                    b.HasOne("WorkflowLib.Models.Network.MicroserviceConfigurations.EndpointType", "EndpointTypeTo")
                        .WithMany()
                        .HasForeignKey("EndpointTypeToId");

                    b.Navigation("EndpointFrom");

                    b.Navigation("EndpointTo");

                    b.Navigation("EndpointTypeFrom");

                    b.Navigation("EndpointTypeTo");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Customers.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Navigation("SubItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessDiagram", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.Navigation("SubProcesses");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Navigation("ChildTasks");

                    b.Navigation("Comments");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Processes.WorkflowInstance", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.Project", b =>
                {
                    b.Navigation("ProjectPhases");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("WorkflowLib.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
