// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowLib.Examples.Delivering.Example01.Contexts;

#nullable disable

namespace WorkflowLib.Examples.Delivering.Example01.Migrations
{
    [DbContext(typeof(DeliveringContext))]
    [Migration("20240519113628_NullbableDateTimeInBusinessModels")]
    partial class NullbableDateTimeInBusinessModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerCompaniesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "CustomerCompaniesId");

                    b.HasIndex("CustomerCompaniesId");

                    b.ToTable("CompanyContract");
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.Property<long>("CompaniesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmployeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompaniesId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("CompanyEmployee");
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("ContractCustomer");
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OurEmployeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "OurEmployeesId");

                    b.HasIndex("OurEmployeesId");

                    b.ToTable("ContractEmployee");
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.Property<long>("ContractsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OurOrganizationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractsId", "OurOrganizationsId");

                    b.HasIndex("OurOrganizationsId");

                    b.ToTable("ContractOrganization");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.BusinessTaskDeliveryOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("BusinessTaskDeliveryOrders");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.InitialOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CookingOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryKitchen2WhId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryWh2KitchenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CookingOperationId");

                    b.HasIndex("DeliveryKitchen2WhId");

                    b.HasIndex("DeliveryWh2KitchenId");

                    b.ToTable("InitialOrders");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditonalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CouldBeCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerUid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartExpected")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutorUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderCustomerType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderExecutorType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProductsPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentOrderId");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Order");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVatRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRMRoleType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmployDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICQ")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplacementMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HeadItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HeadItemId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HardDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationItems");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenDt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrganizationItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationItemId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AuthorChangedId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AuthorCreatedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroupByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorChangedId");

                    b.HasIndex("AuthorCreatedId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Monetary.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payer")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receiver")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessDiagram");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagramElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessDiagramId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDiagramId");

                    b.ToTable("BusinessDiagramElement");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DiagramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.HasIndex("ParentId");

                    b.ToTable("BusinessProcess");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessProcessState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.ToTable("BusinessProcessState");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessProcessStateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartExpected")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExecutorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutorIsEmulationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutorReplacedId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExpiredNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmulation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessStateId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("ExecutorIsEmulationId");

                    b.HasIndex("ExecutorReplacedId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("BusinessTasks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BusinessTask");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.DeliveryOrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("DeliveryOrderProducts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IngredientProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<long?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinalProductId");

                    b.HasIndex("IngredientProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.InitialOrderIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CookingOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryWh2KitchenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InitialOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InitialOrderProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CookingOperationId");

                    b.HasIndex("DeliveryWh2KitchenId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("InitialOrderId");

                    b.HasIndex("InitialOrderProductId");

                    b.ToTable("InitialOrderIngredients");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.InitialOrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CookingOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryKitchen2WhId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryWh2KitchenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InitialOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CookingOperationId");

                    b.HasIndex("DeliveryKitchen2WhId");

                    b.HasIndex("DeliveryWh2KitchenId");

                    b.HasIndex("InitialOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("InitialOrderProducts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.OrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductCategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProductTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveryOrderProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("NewQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("NewStatus")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OldQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("OldStatus")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OrderProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QuantityDelta")
                        .HasColumnType("REAL");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WHProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("DeliveryOrderProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderProductId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WHProductId");

                    b.ToTable("ProductTransfers");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndExpected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartActual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartExpected")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuaranteePeriodInMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<long>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProjectPhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPhase");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProjectPlanItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPlanItemId");

                    b.ToTable("ProjectPlanItem");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.WHProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WHProducts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.RiskManagement.Risk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorChangedId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorCreatedId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorResolvedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentResolved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorChangedId");

                    b.HasIndex("AuthorCreatedId");

                    b.HasIndex("AuthorResolvedId");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Risk");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorCreatedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessEntityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorCreatedId");

                    b.HasIndex("BusinessTaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", b =>
                {
                    b.HasBaseType("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order");

                    b.Property<long?>("DeliveryMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentDeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("ParentDeliveryOrderId");

                    b.HasDiscriminator().HasValue("DeliveryOrder");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Cooking.CookingOperation", b =>
                {
                    b.HasBaseType("WorkflowLib.Shared.Models.Business.Processes.BusinessTask");

                    b.HasDiscriminator().HasValue("CookingOperation");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryOperation", b =>
                {
                    b.HasBaseType("WorkflowLib.Shared.Models.Business.Processes.BusinessTask");

                    b.Property<long?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveryMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.HasIndex("ContactId");

                    b.HasIndex("DeliveryMethodId");

                    b.HasDiscriminator().HasValue("DeliveryOperation");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryKitchen2Wh", b =>
                {
                    b.HasBaseType("WorkflowLib.Shared.Models.Business.Delivery.DeliveryOperation");

                    b.Property<string>("GeneratedOrderQrCode")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DeliveryKitchen2Wh");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryWh2Kitchen", b =>
                {
                    b.HasBaseType("WorkflowLib.Shared.Models.Business.Delivery.DeliveryOperation");

                    b.HasDiscriminator().HasValue("DeliveryWh2Kitchen");
                });

            modelBuilder.Entity("CompanyContract", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CustomerCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyEmployee", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractCustomer", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEmployee", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", null)
                        .WithMany()
                        .HasForeignKey("OurEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractOrganization", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Organization", null)
                        .WithMany()
                        .HasForeignKey("OurOrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.BusinessTaskDeliveryOrder", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", "BusinessTask")
                        .WithMany()
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId");

                    b.Navigation("BusinessTask");

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.InitialOrder", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Cooking.CookingOperation", null)
                        .WithMany("InitialOrders")
                        .HasForeignKey("CookingOperationId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryKitchen2Wh", null)
                        .WithMany("InitialOrders")
                        .HasForeignKey("DeliveryKitchen2WhId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryWh2Kitchen", null)
                        .WithMany("InitialOrders")
                        .HasForeignKey("DeliveryWh2KitchenId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", "ParentOrder")
                        .WithMany()
                        .HasForeignKey("ParentOrderId");

                    b.Navigation("ParentOrder");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Company", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Customer", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Organization", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", "HeadItem")
                        .WithMany()
                        .HasForeignKey("HeadItemId");

                    b.Navigation("Company");

                    b.Navigation("HeadItem");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", "ParentItem")
                        .WithMany("SubItems")
                        .HasForeignKey("ParentItemId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParentItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Skill", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", null)
                        .WithMany("UserAccounts")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationItemId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserGroup", null)
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "AuthorChanged")
                        .WithMany()
                        .HasForeignKey("AuthorChangedId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "AuthorCreated")
                        .WithMany()
                        .HasForeignKey("AuthorCreatedId");

                    b.Navigation("AuthorChanged");

                    b.Navigation("AuthorCreated");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Monetary.Payment", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagramElement", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagram", null)
                        .WithMany("Elements")
                        .HasForeignKey("BusinessDiagramId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagram", "Diagram")
                        .WithMany()
                        .HasForeignKey("DiagramId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessProcess", "Parent")
                        .WithMany("SubProcesses")
                        .HasForeignKey("ParentId");

                    b.Navigation("Diagram");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessProcessState", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessProcess", "BusinessProcess")
                        .WithMany()
                        .HasForeignKey("BusinessProcessId");

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessProcessState", "BusinessProcessState")
                        .WithMany()
                        .HasForeignKey("BusinessProcessStateId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "ExecutorIsEmulation")
                        .WithMany()
                        .HasForeignKey("ExecutorIsEmulationId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "ExecutorReplaced")
                        .WithMany()
                        .HasForeignKey("ExecutorReplacedId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId");

                    b.Navigation("BusinessProcessState");

                    b.Navigation("Executor");

                    b.Navigation("ExecutorIsEmulation");

                    b.Navigation("ExecutorReplaced");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.DeliveryOrderProduct", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("DeliveryOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Ingredient", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "FinalProduct")
                        .WithMany()
                        .HasForeignKey("FinalProductId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "IngredientProduct")
                        .WithMany()
                        .HasForeignKey("IngredientProductId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.Navigation("FinalProduct");

                    b.Navigation("IngredientProduct");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.InitialOrderIngredient", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Cooking.CookingOperation", null)
                        .WithMany("InitialOrderIngredients")
                        .HasForeignKey("CookingOperationId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryWh2Kitchen", null)
                        .WithMany("InitialOrderIngredients")
                        .HasForeignKey("DeliveryWh2KitchenId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.InitialOrder", "InitialOrder")
                        .WithMany()
                        .HasForeignKey("InitialOrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.InitialOrderProduct", "InitialOrderProduct")
                        .WithMany()
                        .HasForeignKey("InitialOrderProductId");

                    b.Navigation("Ingredient");

                    b.Navigation("InitialOrder");

                    b.Navigation("InitialOrderProduct");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.InitialOrderProduct", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Cooking.CookingOperation", null)
                        .WithMany("InitialOrderProducts")
                        .HasForeignKey("CookingOperationId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryKitchen2Wh", null)
                        .WithMany("InitialOrderProducts")
                        .HasForeignKey("DeliveryKitchen2WhId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryWh2Kitchen", null)
                        .WithMany("InitialOrderProducts")
                        .HasForeignKey("DeliveryWh2KitchenId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.InitialOrder", "InitialOrder")
                        .WithMany()
                        .HasForeignKey("InitialOrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("InitialOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.OrderProduct", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Product", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProductTransfer", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", "DeliveryOrder")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.DeliveryOrderProduct", "DeliveryOrderProduct")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderProductId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.OrderProduct", "OrderProduct")
                        .WithMany()
                        .HasForeignKey("OrderProductId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.ProductTransfer", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.WHProduct", "WHProduct")
                        .WithMany()
                        .HasForeignKey("WHProductId");

                    b.Navigation("DeliveryOrder");

                    b.Navigation("DeliveryOrderProduct");

                    b.Navigation("Order");

                    b.Navigation("OrderProduct");

                    b.Navigation("Parent");

                    b.Navigation("WHProduct");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Project", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProjectPhase", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Project", "Project")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("ProjectId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.ProjectPlanItem", "ProjectPlanItem")
                        .WithMany()
                        .HasForeignKey("ProjectPlanItemId");

                    b.Navigation("Project");

                    b.Navigation("ProjectPlanItem");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.ProjectPlanItem", null)
                        .WithMany("Items")
                        .HasForeignKey("ProjectPlanItemId");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Recipe", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.WHProduct", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.RiskManagement.Risk", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", "AuthorChanged")
                        .WithMany()
                        .HasForeignKey("AuthorChangedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", "AuthorCreated")
                        .WithMany()
                        .HasForeignKey("AuthorCreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", "AuthorResolved")
                        .WithMany()
                        .HasForeignKey("AuthorResolvedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Risks")
                        .HasForeignKey("BusinessTaskId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Products.Project", null)
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AuthorChanged");

                    b.Navigation("AuthorCreated");

                    b.Navigation("AuthorResolved");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.SocialCommunication.Comment", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.InformationSystem.UserAccount", "AuthorCreated")
                        .WithMany()
                        .HasForeignKey("AuthorCreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", null)
                        .WithMany("Comments")
                        .HasForeignKey("BusinessTaskId");

                    b.Navigation("AuthorCreated");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.BusinessDocuments.DeliveryOrder", "ParentDeliveryOrder")
                        .WithMany()
                        .HasForeignKey("ParentDeliveryOrderId");

                    b.Navigation("DeliveryMethod");

                    b.Navigation("ParentDeliveryOrder");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryOperation", b =>
                {
                    b.HasOne("WorkflowLib.Shared.Models.Business.Customers.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("WorkflowLib.Shared.Models.Business.Delivery.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId");

                    b.Navigation("Contact");

                    b.Navigation("DeliveryMethod");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.BusinessDocuments.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Customers.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.Employee", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.OrganizationItem", b =>
                {
                    b.Navigation("SubItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.InformationSystem.UserGroup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessDiagram", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessProcess", b =>
                {
                    b.Navigation("SubProcesses");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Processes.BusinessTask", b =>
                {
                    b.Navigation("ChildTasks");

                    b.Navigation("Comments");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Project", b =>
                {
                    b.Navigation("ProjectPhases");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.ProjectPlanItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Products.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Cooking.CookingOperation", b =>
                {
                    b.Navigation("InitialOrderIngredients");

                    b.Navigation("InitialOrderProducts");

                    b.Navigation("InitialOrders");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryKitchen2Wh", b =>
                {
                    b.Navigation("InitialOrderProducts");

                    b.Navigation("InitialOrders");
                });

            modelBuilder.Entity("WorkflowLib.Shared.Models.Business.Delivery.DeliveryWh2Kitchen", b =>
                {
                    b.Navigation("InitialOrderIngredients");

                    b.Navigation("InitialOrderProducts");

                    b.Navigation("InitialOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
