-- Production. 
INSERT INTO mp.nationality (name) VALUES ('USA'); 
INSERT INTO mp.nationality (name) VALUES ('Canada'); 
INSERT INTO mp.nationality (name) VALUES ('Mexico'); 
INSERT INTO mp.nationality (name) VALUES ('Russia'); 
INSERT INTO mp.nationality (name) VALUES ('Poland'); 
INSERT INTO mp.nationality (name) VALUES ('Ukraine'); 
INSERT INTO mp.nationality (name) VALUES ('Belarus'); 
INSERT INTO mp.nationality (name) VALUES ('Luxembourg'); 
INSERT INTO mp.nationality (name) VALUES ('France'); 
INSERT INTO mp.nationality (name) VALUES ('Denmark'); 
INSERT INTO mp.nationality (name) VALUES ('Germany'); 
INSERT INTO mp.nationality (name) VALUES ('Austria'); 
INSERT INTO mp.nationality (name) VALUES ('Argentina'); 
INSERT INTO mp.nationality (name) VALUES ('Brazil'); 
INSERT INTO mp.nationality (name) VALUES ('Chile'); 
INSERT INTO mp.nationality (name) VALUES ('Uruguay'); 
INSERT INTO mp.nationality (name) VALUES ('Paraguay'); 
INSERT INTO mp.nationality (name) VALUES ('Bolivia'); 
INSERT INTO mp.nationality (name) VALUES ('Peru'); 
INSERT INTO mp.nationality (name) VALUES ('Colombia'); 
INSERT INTO mp.nationality (name) VALUES ('Venezuela'); 
INSERT INTO mp.nationality (name) VALUES ('Ecuador'); 
INSERT INTO mp.nationality (name) VALUES ('Guyana'); 
INSERT INTO mp.nationality (name) VALUES ('Suriname'); 
INSERT INTO mp.nationality (name) VALUES ('French Guiana'); 
INSERT INTO mp.nationality (name) VALUES ('Caribbean'); 
INSERT INTO mp.nationality (name) VALUES ('Japan'); 
INSERT INTO mp.nationality (name) VALUES ('South Korea'); 
INSERT INTO mp.nationality (name) VALUES ('North Korea'); 
INSERT INTO mp.nationality (name) VALUES ('Mongolia'); 
INSERT INTO mp.nationality (name) VALUES ('China'); 
INSERT INTO mp.nationality (name) VALUES ('India'); 
INSERT INTO mp.nationality (name) VALUES ('Thailand'); 
INSERT INTO mp.nationality (name) VALUES ('Thaiwan'); 
INSERT INTO mp.nationality (name) VALUES ('Vietnam'); 
INSERT INTO mp.nationality (name) VALUES ('Laos'); 
INSERT INTO mp.nationality (name) VALUES ('Cambodia'); 
INSERT INTO mp.nationality (name) VALUES ('Philippines'); 
INSERT INTO mp.nationality (name) VALUES ('Fiji'); 
INSERT INTO mp.nationality (name) VALUES ('Solomon Islands'); 
INSERT INTO mp.nationality (name) VALUES ('New Caledonia'); 
INSERT INTO mp.nationality (name) VALUES ('New Zeland'); 
INSERT INTO mp.nationality (name) VALUES ('Australia'); 
INSERT INTO mp.nationality (name) VALUES ('Indonesia'); 
INSERT INTO mp.nationality (name) VALUES ('Malaysia'); 
INSERT INTO mp.nationality (name) VALUES ('Belgium'); 
INSERT INTO mp.nationality (name) VALUES ('Netherlands'); 
INSERT INTO mp.nationality (name) VALUES ('Portugal'); 
INSERT INTO mp.nationality (name) VALUES ('Spain'); 
INSERT INTO mp.nationality (name) VALUES ('Italy'); 
INSERT INTO mp.nationality (name) VALUES ('Greece'); 
INSERT INTO mp.nationality (name) VALUES ('Bulgaria'); 
INSERT INTO mp.nationality (name) VALUES ('Moldova'); 
INSERT INTO mp.nationality (name) VALUES ('Estonia'); 
INSERT INTO mp.nationality (name) VALUES ('Latvia'); 
INSERT INTO mp.nationality (name) VALUES ('Lithuania'); 
INSERT INTO mp.nationality (name) VALUES ('Hungary'); 
INSERT INTO mp.nationality (name) VALUES ('Romania'); 
INSERT INTO mp.nationality (name) VALUES ('Croatia'); 
INSERT INTO mp.nationality (name) VALUES ('Slovenia'); 
INSERT INTO mp.nationality (name) VALUES ('Serbia'); 
INSERT INTO mp.nationality (name) VALUES ('Macedonia'); 
INSERT INTO mp.nationality (name) VALUES ('Turkey'); 
INSERT INTO mp.nationality (name) VALUES ('Israel'); 
INSERT INTO mp.nationality (name) VALUES ('Cyprus'); 
INSERT INTO mp.nationality (name) VALUES ('Syria'); 
INSERT INTO mp.nationality (name) VALUES ('Lybia'); 
INSERT INTO mp.nationality (name) VALUES ('Great Britain'); 
INSERT INTO mp.nationality (name) VALUES ('Ireland'); 
INSERT INTO mp.nationality (name) VALUES ('Iceland'); 
INSERT INTO mp.nationality (name) VALUES ('Sweden'); 
INSERT INTO mp.nationality (name) VALUES ('Norway'); 
INSERT INTO mp.nationality (name) VALUES ('Finland'); 
INSERT INTO mp.nationality (name) VALUES ('Switzerland'); 
INSERT INTO mp.nationality (name) VALUES ('Czech Republic'); 
INSERT INTO mp.nationality (name) VALUES ('Slovakia'); 
INSERT INTO mp.nationality (name) VALUES ('Kazakhstan'); 
INSERT INTO mp.nationality (name) VALUES ('Uzbekistan'); 
INSERT INTO mp.nationality (name) VALUES ('Tajikistan'); 
INSERT INTO mp.nationality (name) VALUES ('Turkmenistan'); 
INSERT INTO mp.nationality (name) VALUES ('Kirgizstan'); 
INSERT INTO mp.nationality (name) VALUES ('Iran'); 
INSERT INTO mp.nationality (name) VALUES ('Iraq'); 
INSERT INTO mp.nationality (name) VALUES ('Kuwait'); 
INSERT INTO mp.nationality (name) VALUES ('Qatar'); 
INSERT INTO mp.nationality (name) VALUES ('Bangladesh'); 
INSERT INTO mp.nationality (name) VALUES ('Jordan'); 
INSERT INTO mp.nationality (name) VALUES ('Saudi Arabia'); 
INSERT INTO mp.nationality (name) VALUES ('UAE'); 
INSERT INTO mp.nationality (name) VALUES ('Lebanon'); 
INSERT INTO mp.nationality (name) VALUES ('Yemen'); 
INSERT INTO mp.nationality (name) VALUES ('Oman'); 
INSERT INTO mp.nationality (name) VALUES ('Azerbaijan'); 
INSERT INTO mp.nationality (name) VALUES ('Georgia'); 
INSERT INTO mp.nationality (name) VALUES ('Pakistan'); 
INSERT INTO mp.nationality (name) VALUES ('Afganistan'); 
INSERT INTO mp.nationality (name) VALUES ('Kongo'); 
INSERT INTO mp.nationality (name) VALUES ('Egypt'); 
INSERT INTO mp.nationality (name) VALUES ('Morocco'); 
INSERT INTO mp.nationality (name) VALUES ('Tunisia'); 
INSERT INTO mp.nationality (name) VALUES ('Libya'); 
INSERT INTO mp.nationality (name) VALUES ('Algeria'); 
INSERT INTO mp.nationality (name) VALUES ('Western Sahara'); 
INSERT INTO mp.nationality (name) VALUES ('Mauritius'); 
INSERT INTO mp.nationality (name) VALUES ('Mali'); 
INSERT INTO mp.nationality (name) VALUES ('Sudan'); 
INSERT INTO mp.nationality (name) VALUES ('South Sudan'); 
INSERT INTO mp.nationality (name) VALUES ('Ethiopia'); 
INSERT INTO mp.nationality (name) VALUES ('Somalia'); 
INSERT INTO mp.nationality (name) VALUES ('Madagascar'); 
INSERT INTO mp.nationality (name) VALUES ('Kenya'); 
INSERT INTO mp.nationality (name) VALUES ('Benin'); 
INSERT INTO mp.nationality (name) VALUES ('CAR'); 
INSERT INTO mp.nationality (name) VALUES ('South Africa'); 
INSERT INTO mp.nationality (name) VALUES ('Malawi'); 
INSERT INTO mp.nationality (name) VALUES ('Mozambique'); 
INSERT INTO mp.nationality (name) VALUES ('Angola'); 

INSERT INTO mp.gender (name) VALUES ('Male'); 
INSERT INTO mp.gender (name) VALUES ('Female'); 


-- For tests. 
INSERT INTO test.nationality (name) VALUES ('USA'); 
INSERT INTO test.nationality (name) VALUES ('Canada'); 
INSERT INTO test.nationality (name) VALUES ('Mexico'); 
INSERT INTO test.nationality (name) VALUES ('Russia'); 
INSERT INTO test.nationality (name) VALUES ('Poland'); 
INSERT INTO test.nationality (name) VALUES ('Ukraine'); 
INSERT INTO test.nationality (name) VALUES ('Belarus'); 
INSERT INTO test.nationality (name) VALUES ('Luxembourg'); 
INSERT INTO test.nationality (name) VALUES ('France'); 
INSERT INTO test.nationality (name) VALUES ('Denmark'); 
INSERT INTO test.nationality (name) VALUES ('Germany'); 
INSERT INTO test.nationality (name) VALUES ('Austria'); 

INSERT INTO test.gender (name) VALUES ('Male'); 
INSERT INTO test.gender (name) VALUES ('Female'); 
