-- Insert data into public."LanguageKeyValuePairs".

INSERT INTO public."LanguageKeyValuePairs" ("Key", "Value", "LanguageType")
VALUES
    ('EmployeeManagementSystem', 'Employee Management System', 2),
    ('EmployeeManagementSystem.Description', 'This app allows you to effectively manage employee information', 2),
    ('Notifications', 'Notifications', 2),
    ('Page.Home', 'Home', 2),
    ('MyAccount', 'My Account', 2),
    ('SignIn', 'Sign In', 2),
    ('SignOut', 'Sign Out', 2),
    ('UserAccount.Username', 'Username', 2),
    ('UserAccount.Password', 'Password', 2),
    ('UserGroup', 'User group', 2),
    ('Parameter', 'Parameter', 2),
    ('Value', 'Value', 2),
    ('Name', 'Name', 2),
    ('Description', 'Description', 2),
    ('HeadItem', 'Head item', 2),
    ('ParentItem', 'Parent item', 2),
    ('Additional', 'Additional', 2),
    ('OrganizationalStructure', 'Organizational structure', 2),
    ('BriefDescription', 'Brief description', 2),
    ('Employees', 'Employees', 2),
    ('Hiring', 'Hiring specialists', 2),
    ('Customers', 'Customers', 2),
    ('Organizations', 'Organizations', 2),
    ('OrganizationDetails', 'Organization details', 2),
    ('OrganizationItem', 'Organization item', 2),
    ('OrganizationItemDetails', 'Organization item details', 2),
    ('Organization', 'Organization', 2),
    ('Departments', 'Departments', 2),
    ('Teams', 'Teams', 2),
    ('JobPositions', 'Job positions', 2),
    ('Absenses', 'Absenses', 2),
    ('Vacations', 'Vacations', 2),
    ('AbsenseFilters', 'Absense filters', 2),
    ('AbsenseReason', 'Absense reason', 2),
    ('Note', 'Note', 2),
    ('NewVacation', 'New vacation', 2),
    ('NewVacation.Add', 'Add new vacation', 2),
    ('NewVacation.Note01', 'Make sure that the employee with the specified full name exists in the initial dataset', 2),
    ('NewVacation.Note02', 'If such user does not exist, contact admins to add the employee', 2),
    ('NewVacation.Note03', 'Employee''s full name should be exactly the same as specified in the initial dataset', 2),
    ('FirstName', 'First name', 2),
    ('MiddleName', 'Middle name', 2),
    ('LastName', 'Last name', 2),
    ('FullName', 'Full name', 2),
    ('FullName.Enter', 'Enter full name', 2),
    ('FullName.CurrentEmployee', 'Current employee''s full name', 2),
    ('Gender', 'Gender', 2),
    ('Gender.Male', 'Male', 2),
    ('Gender.Female', 'Female', 2),
    ('JobTitle', 'Job title', 2),
    ('JobTitle.ChiefExecutiveOfficer', 'Chief Executive Officer', 2),
    ('JobTitle.VicePresident', 'Vice President', 2),
    ('JobTitle.Director', 'Director', 2),
    ('JobTitle.HRManager', 'HR Manager', 2),
    ('JobTitle.ProjectManager', 'Project Manager', 2),
    ('JobTitle.FrontendDeveloper', 'Frontend Developer', 2),
    ('JobTitle.BackendDeveloper', 'Backend Developer', 2),
    ('JobTitle.FullstackDeveloper', 'Fullstack Developer', 2),
    ('JobTitle.DevelopmentLead', 'Development Lead', 2),
    ('JobTitle.QAEngineer', 'QA Engineer', 2),
    ('Department', 'Department', 2),
    ('Department.ERPDevelopment', 'ERP Development', 2),
    ('Department.HRMDevelopment', 'HRM Development', 2),
    ('Department.CRMDevelopment', 'CRM Development', 2),
    ('Department.HR', 'HR', 2),
    ('Department.Administration', 'Administration', 2),
    ('BirthDate', 'Birth date', 2),
    ('Age', 'Age', 2),
    ('MinimumAge', 'Minimum age', 2),
    ('MinimumAge.Enter', 'Enter age (min.)', 2),
    ('MaximumAge', 'Maximum age', 2),
    ('MaximumAge.Enter', 'Enter age (max.)', 2),
    ('EmployDate', 'Employ date', 2),
    ('BeginDate', 'Begin date', 2),
    ('EndDate', 'End date', 2),
    ('Find', 'Find', 2),
    ('Filters', 'Filters', 2),
    ('CurrentEmployee', 'Current employee', 2),
    ('FilterOptions', 'Filter options', 2),
    ('FilterOptions.NoFiltersApplied', 'No filters applied', 2),
    ('FilterOptions.ShowEmployee', 'Show employee', 2),
    ('FilterOptions.ExcludeEmployee', 'Exclude employee', 2),
    ('FilterOptions.ShowAllFilteredVacations', 'Show all filtered vacations', 2),
    ('FilterOptions.ShowIntersections', 'Show intersections', 2),
    ('FilterOptions.ExcludeIntersections', 'Exclude intersections', 2),
    ('Error.DataNotGeneratedYet', 'Data not generated yet...', 2),
    ('More', 'More', 2),
    ('MobilePhone', 'Mobile Phone', 2),
    ('WorkPhone', 'Work Phone', 2),
    ('Documents', 'Documents', 2),
    ('Documents.Internal', 'Internal documentation', 2),
    ('KnowledgeBase', 'Knowledge base', 2);

INSERT INTO public."LanguageKeyValuePairs" ("Key", "Value", "LanguageType")
VALUES
    ('EmployeeManagementSystem', 'Система управления персоналом', 3),
    ('EmployeeManagementSystem.Description', 'Данное приложение позволяет эффективно управлять информацией о сотрудниках', 3),
    ('Notifications', 'Уведомления', 3),
    ('Page.Home', 'Главная', 3),
    ('MyAccount', 'Мой аккаунт', 3),
    ('SignIn', 'Войти', 3),
    ('SignOut', 'Выйти', 3),
    ('UserAccount.Username', 'Имя пользователя', 3),
    ('UserAccount.Password', 'Пароль', 3),
    ('UserGroup', 'Группа пользователей', 3),
    ('Parameter', 'Параметер', 3),
    ('Value', 'Значение', 3),
    ('Name', 'Наименование', 3),
    ('Description', 'Описание', 3),
    ('HeadItem', 'Главный элемент', 3),
    ('ParentItem', 'Родительский элемент', 3),
    ('Additional', 'Дополнительно', 3),
    ('OrganizationalStructure', 'Организационная структура', 3),
    ('BriefDescription', 'Краткое описание', 3),
    ('Employees', 'Сотрудники', 3),
    ('Hiring', 'Найм специалистов', 3),
    ('Customers', 'Потребители', 3),
    ('Organizations', 'Организации', 3),
    ('OrganizationDetails', 'Детали организации', 3),
    ('OrganizationItem', 'Организационный элемент', 3),
    ('OrganizationItemDetails', 'Детали организационного элемента', 3),
    ('Organization', 'Организация', 3),
    ('Departments', 'Департаменты', 3),
    ('Teams', 'Команды', 3),
    ('JobPositions', 'Должности', 3),
    ('Absenses', 'Отсутствия', 3),
    ('Vacations', 'Отпуска', 3),
    ('AbsenseFilters', 'Фильтры по отсутствиям', 3),
    ('AbsenseReason', 'Причина отсутствия', 3),
    ('Note', 'Примечание', 3),
    ('NewVacation', 'Новый отпуск', 3),
    ('NewVacation.Add', 'Добавить новый отпуск', 3),
    ('NewVacation.Note01', 'Убедитесь, что сотрудник с указанным полным именем существует в исходном наборе данных', 3),
    ('NewVacation.Note02', 'Если такого пользователя не существует, обратитесь к администраторам, чтобы добавить сотрудника', 3),
    ('NewVacation.Note03', 'Полное имя сотрудника должно быть точно таким же, как указано в исходном наборе данных', 3),
    ('FirstName', 'Личное имя', 3),
    ('MiddleName', 'Среднее имя (или отчество)', 3),
    ('LastName', 'Фамилия', 3),
    ('FullName', 'Полное имя', 3),
    ('FullName.Enter', 'Введите полное имя', 3),
    ('FullName.CurrentEmployee', 'Полное имя текущего пользователя', 3),
    ('Gender', 'Пол', 3),
    ('Gender.Male', 'Мужской', 3),
    ('Gender.Female', 'Женский', 3),
    ('JobTitle', 'Должность', 3),
    ('JobTitle.ChiefExecutiveOfficer', 'Директор компании', 3),
    ('JobTitle.VicePresident', 'Вице-президент', 3),
    ('JobTitle.Director', 'Директор', 3),
    ('JobTitle.HRManager', 'HR-менеджер', 3),
    ('JobTitle.ProjectManager', 'Project-менеджер', 3),
    ('JobTitle.FrontendDeveloper', 'Frontend-разработчик', 3),
    ('JobTitle.BackendDeveloper', 'Backend-разработчик', 3),
    ('JobTitle.FullstackDeveloper', 'Fullstack-разработчик', 3),
    ('JobTitle.DevelopmentLead', 'Руководитель разработки', 3),
    ('JobTitle.QAEngineer', 'QA-инженер', 3),
    ('Department', 'Департамент', 3),
    ('Department.ERPDevelopment', 'ERP разработка', 3),
    ('Department.HRMDevelopment', 'HRM разработка', 3),
    ('Department.CRMDevelopment', 'CRM разработка', 3),
    ('Department.HR', 'HR', 3),
    ('Department.Administration', 'Администрация', 3),
    ('BirthDate', 'Дата рождения', 3),
    ('Age', 'Возраст', 3),
    ('MinimumAge', 'Минимальный возраст', 3),
    ('MinimumAge.Enter', 'Введите возраст (мин.)', 3),
    ('MaximumAge', 'Максимальный возраст', 3),
    ('MaximumAge.Enter', 'Введите возраст (макс.)', 3),
    ('EmployDate', 'Дата трудоустройства', 3),
    ('BeginDate', 'Дата начала', 3),
    ('EndDate', 'Дата конца', 3),
    ('Find', 'Найти', 3),
    ('Filters', 'Фильтры', 3),
    ('CurrentEmployee', 'Текущий сотрудник', 3),
    ('FilterOptions', 'Опции фильтра', 3),
    ('FilterOptions.NoFiltersApplied', 'Фильтры не применены', 3),
    ('FilterOptions.ShowEmployee', 'Показать сотрудника', 3),
    ('FilterOptions.ExcludeEmployee', 'Скрыть сотрудника', 3),
    ('FilterOptions.ShowAllFilteredVacations', 'Показать фильтрованные отпуска', 3),
    ('FilterOptions.ShowIntersections', 'Показать пересечения', 3),
    ('FilterOptions.ExcludeIntersections', 'Скрыть пересечения', 3),
    ('Error.DataNotGeneratedYet', 'Данные ещё не сгенерированы...', 3),
    ('More', 'Больше', 3),
    ('MobilePhone', 'Мобильный телефон', 3),
    ('WorkPhone', 'Рабочий телефон', 3),
    ('Documents', 'Документы', 3),
    ('Documents.Internal', 'Внутренняя документация', 3),
    ('KnowledgeBase', 'База знаний', 3);

INSERT INTO public."LanguageKeyValuePairs" ("Key", "Value", "LanguageType")
VALUES
    ('EmployeeManagementSystem', 'Mitarbeiterverwaltungssystem', 4),
    ('EmployeeManagementSystem.Description', 'Mit dieser App können Sie Mitarbeiterinformationen effektiv verwalten', 4),
    ('Notifications', 'Benachrichtigungen', 4),
    ('Page.Home', 'Startseite', 4),
    ('MyAccount', 'Mein Konto', 4),
    ('SignIn', 'Einloggen', 4),
    ('SignOut', 'Ausloggen', 4),
    ('UserAccount.Username', 'Benutzername', 4),
    ('UserAccount.Password', 'Passwort', 4),
    ('UserGroup', 'Benutzergruppe', 4),
    ('Parameter', 'Parameter', 4),
    ('Value', 'Wert', 4),
    ('Name', 'Name', 4),
    ('Description', 'Beschreibung', 4),
    ('HeadItem', 'Kopfelement', 4),
    ('ParentItem', 'Übergeordnetes Element', 4),
    ('Additional', 'Zusätzlich', 4),
    ('OrganizationalStructure', 'Organisatorische Struktur', 4),
    ('BriefDescription', 'Kurzbeschreibung', 4),
    ('Employees', 'Mitarbeiter', 4),
    ('Hiring', 'Spezialisten einstellen', 4),
    ('Customers', 'Kunden', 4),
    ('Organizations', 'Organisationen', 4),
    ('OrganizationDetails', 'Organisationsdetails', 4),
    ('OrganizationItem', 'Organisationselement', 4),
    ('OrganizationItemDetails', 'Details des Organisationselements', 4),
    ('Organization', 'Organisation', 4),
    ('Departments', 'Abteilungen', 4),
    ('Teams', 'Teams', 4),
    ('JobPositions', 'Stellenangebote', 4),
    ('Absenses', 'Abwesenheiten', 4),
    ('Vacations', 'Urlaub', 4),
    ('AbsenseFilters', 'Abwesenheitsfilter', 4),
    ('AbsenseReason', 'Abwesenheitsgrund', 4),
    ('Note', 'Notiz', 4),
    ('NewVacation', 'Neuer Urlaub', 4),
    ('NewVacation.Add', 'Neuen Urlaub hinzufügen', 4),
    ('NewVacation.Note01', 'Stellen Sie sicher, dass der Mitarbeiter mit dem angegebenen vollständigen Namen im Ausgangsdatensatz vorhanden ist', 4),
    ('NewVacation.Note02', 'Wenn ein solcher Benutzer nicht existiert, wenden Sie sich an die Administratoren, um den Mitarbeiter hinzuzufügen', 4),
    ('NewVacation.Note03', 'Der vollständige Name des Mitarbeiters muss genau dem im ursprünglichen Datensatz angegebenen entsprechen', 4),
    ('FirstName', 'Vorname', 4),
    ('MiddleName', 'Zweitname', 4),
    ('LastName', 'Nachname', 4),
    ('FullName', 'Vollständiger Name', 4),
    ('FullName.Enter', 'Vollständigen Namen eingeben', 4),
    ('FullName.CurrentEmployee', 'Vollständiger Name des aktuellen Mitarbeiters', 4),
    ('Gender', 'Geschlecht', 4),
    ('Gender.Male', 'Männlich', 4),
    ('Gender.Female', 'Weiblich', 4),
    ('JobTitle', 'Berufsbezeichnung', 4),
    ('JobTitle.ChiefExecutiveOfficer', 'Geschäftsführer', 4),
    ('JobTitle.VicePresident', 'Vizepräsident', 4),
    ('JobTitle.Director', 'Direktor', 4),
    ('JobTitle.HRManager', 'HR Manager', 4),
    ('JobTitle.ProjectManager', 'Project Manager', 4),
    ('JobTitle.FrontendDeveloper', 'Frontend-Entwickler', 4),
    ('JobTitle.BackendDeveloper', 'Backend-Entwickler', 4),
    ('JobTitle.FullstackDeveloper', 'Fullstack-Entwickler', 4),
    ('JobTitle.DevelopmentLead', 'Entwicklungsleiter', 4),
    ('JobTitle.QAEngineer', 'QA-Ingenieur', 4),
    ('Department', 'Abteilung', 4),
    ('Department.ERPDevelopment', 'ERP-Entwicklung', 4),
    ('Department.HRMDevelopment', 'HRM-Entwicklung', 4),
    ('Department.CRMDevelopment', 'CRM-Entwicklung', 4),
    ('Department.HR', 'HR', 4),
    ('Department.Administration', 'Administration', 4),
    ('BirthDate', 'Geburtsdatum', 4),
    ('Age', 'Alter', 4),
    ('MinimumAge', 'Mindestalter', 4),
    ('MinimumAge.Enter', 'Alter eingeben (min.)', 4),
    ('MaximumAge', 'Maximalalter', 4),
    ('MaximumAge.Enter', 'Alter eingeben (max.)', 4),
    ('EmployDate', 'Beschäftigungsdatum', 4),
    ('BeginDate', 'Beginndatum', 4),
    ('EndDate', 'Enddatum', 4),
    ('Find', 'Suchen', 4),
    ('Filters', 'Filter', 4),
    ('CurrentEmployee', 'Aktueller Mitarbeiter', 4),
    ('FilterOptions', 'Filteroptionen', 4),
    ('FilterOptions.NoFiltersApplied', 'Keine Filter angewendet', 4),
    ('FilterOptions.ShowEmployee', 'Mitarbeiter anzeigen', 4),
    ('FilterOptions.ExcludeEmployee', 'Mitarbeiter ausblenden', 4),
    ('FilterOptions.ShowAllFilteredVacations', 'Gefilterte Urlaube anzeigen', 4),
    ('FilterOptions.ShowIntersections', 'Schnittpunkte anzeigen', 4),
    ('FilterOptions.ExcludeIntersections', 'Schnittpunkte ausblenden', 4),
    ('Error.DataNotGeneratedYet', 'Daten noch nicht generiert...', 4),
    ('More', 'Mehr', 4),
    ('MobilePhone', 'Mobiltelefon', 4),
    ('WorkPhone', 'Arbeitstelefon', 4),
    ('Documents', 'Unterlagen', 4),
    ('Documents.Internal', 'Interne Unterlagen', 4),
    ('KnowledgeBase', 'Wissensdatenbank', 4);

INSERT INTO public."LanguageKeyValuePairs" ("Key", "Value", "LanguageType")
VALUES
    ('EmployeeManagementSystem', 'Sistema de gestión de empleados', 5),
    ('EmployeeManagementSystem.Description', 'Esta aplicación le permite administrar de manera efectiva la información de los empleados', 5),
    ('Notifications', 'Notificaciones', 5),
    ('Page.Home', 'Inicio', 5),
    ('MyAccount', 'Mi cuenta', 5),
    ('SignIn', 'Iniciar sesión', 5),
    ('SignOut', 'Cerrar sesión', 5),
    ('UserAccount.Username', 'Nombre de usuario', 5),
    ('UserAccount.Password', 'Contraseña', 5),
    ('UserGroup', 'Grupo de usuarios', 5),
    ('Parameter', 'Parámetro', 5),
    ('Value', 'Valor', 5),
    ('Name', 'Nombre', 5),
    ('Description', 'Descripción', 5),
    ('HeadItem', 'Elemento principal', 5),
    ('ParentItem', 'Elemento padre', 5),
    ('Additional', 'Adicional', 5),
    ('OrganizationalStructure', 'Estructura organizacional', 5),
    ('BriefDescription', 'Breve descripción', 5),
    ('Employees', 'Empleados', 5),
    ('Hiring', 'Contratar especialistas', 5),
    ('Customers', 'Clientes', 5),
    ('Organizations', 'Organizaciones', 5),
    ('OrganizationDetails', 'Detalles de la organización', 5),
    ('OrganizationItem', 'Elemento de la organización', 5),
    ('OrganizationItemDetails', 'Detalles del elemento de la organización', 5),
    ('Organization', 'Organizacion', 5),
    ('Departments', 'Departamentos', 5),
    ('Teams', 'Equipos', 5),
    ('JobPositions', 'Puestos de trabajo', 5),
    ('Absenses', 'Ausencias', 5),
    ('Vacations', 'Vacaciones', 5),
    ('AbsenseFilters', 'Filtros de ausencia', 5),
    ('AbsenseReason', 'Motivo de la ausencia', 5),
    ('Note', 'Nota', 5),
    ('NewVacation', 'Nuevas vacaciones', 5),
    ('NewVacation.Add', 'Agregar nuevas vacaciones', 5),
    ('NewVacation.Note01', 'Asegúrese de que el empleado con el nombre completo especificado exista en el conjunto de datos inicial', 5),
    ('NewVacation.Note02', 'Si dicho usuario no existe, comuníquese con los administradores para agregar al empleado', 5),
    ('NewVacation.Note03', 'El nombre completo del empleado debe ser exactamente el mismo que el especificado en el conjunto de datos inicial', 5),
    ('FirstName', 'Primer nombre', 5),
    ('MiddleName', 'Nombre medio', 5),
    ('LastName', 'Apellido', 5),
    ('FullName', 'Nombre completo', 5),
    ('FullName.Enter', 'Ingrese el nombre completo', 5),
    ('FullName.CurrentEmployee', 'Nombre completo del empleado actual', 5),
    ('Gender', 'Género', 5),
    ('Gender.Male', 'Hombre', 5),
    ('Gender.Female', 'Mujer', 5),
    ('JobTitle', 'Declaración de responsabilidad', 5),
    ('JobTitle.ChiefExecutiveOfficer', 'Director ejecutivo', 5),
    ('JobTitle.VicePresident', 'Vicepresidente', 5),
    ('JobTitle.Director', 'Director', 5),
    ('JobTitle.HRManager', 'Gerente de Recursos Humanos', 5),
    ('JobTitle.ProjectManager', 'Gerente de proyectos', 5),
    ('JobTitle.FrontendDeveloper', 'Desarrollador de front-end', 5),
    ('JobTitle.BackendDeveloper', 'Desarrollador de backend', 5),
    ('JobTitle.FullstackDeveloper', 'Desarrollador de fullstack', 5),
    ('JobTitle.DevelopmentLead', 'Líder de desarrollo', 5),
    ('JobTitle.QAEngineer', 'Ingeniero de control de calidad', 5),
    ('Department', 'Departamento', 5),
    ('Department.ERPDevelopment', 'Desarrollo de ERP', 5),
    ('Department.HRMDevelopment', 'Desarrollo de HRM', 5),
    ('Department.CRMDevelopment', 'Desarrollo de CRM', 5),
    ('Department.HR', 'Recursos Humanos', 5),
    ('Department.Administration', 'Administración', 5),
    ('BirthDate', 'Fecha de nacimiento', 5),
    ('Age', 'Edad', 5),
    ('MinimumAge', 'Edad mínima', 5),
    ('MinimumAge.Enter', 'Introducir edad (mín.)', 5),
    ('MaximumAge', 'Edad máxima', 5),
    ('MaximumAge.Enter', 'Introducir edad (máx.)', 5),
    ('EmployDate', 'Fecha de empleo', 5),
    ('BeginDate', 'Fecha inicio', 5),
    ('EndDate', 'Fecha final', 5),
    ('Find', 'Buscar', 5),
    ('Filters', 'Filtros', 5),
    ('CurrentEmployee', 'Empleado actual', 5),
    ('FilterOptions', 'Opciones de filtro', 5),
    ('FilterOptions.NoFiltersApplied', 'No se aplicaron filtros', 5),
    ('FilterOptions.ShowEmployee', 'Mostrar empleado', 5),
    ('FilterOptions.ExcludeEmployee', 'Ocultar empleado', 5),
    ('FilterOptions.ShowAllFilteredVacations', 'Mostrar vacaciones filtradas', 5),
    ('FilterOptions.ShowIntersections', 'Mostrar intersecciones', 5),
    ('FilterOptions.ExcludeIntersections', 'Ocultar intersecciones', 5),
    ('Error.DataNotGeneratedYet', 'Datos aún no generados...', 5),
    ('More', 'Más', 5),
    ('MobilePhone', 'Teléfono móvil', 5),
    ('WorkPhone', 'Teléfono del trabajo', 5),
    ('Documents', 'Documentos', 5),
    ('Documents.Internal', 'Documentación interna', 5),
    ('KnowledgeBase', 'Base de conocimientos', 5);

-- Insert data into public."LanguageKeyForms"

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('MyAccount', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('Parameter', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('Value', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('FirstName', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('MiddleName', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('LastName', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('FullName', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('BirthDate', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('Gender', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('UserAccount.Username', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('MobilePhone', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('WorkPhone', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('OrganizationItem', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('UserGroup', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('EmployDate', 'Auth/MyAccount', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('SignIn', 'Auth/SignIn', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('UserAccount.Username', 'Auth/SignIn', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('UserAccount.Password', 'Auth/SignIn', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('Documents.Internal', 'Documents/Internal', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('KnowledgeBase', 'Documents/KnowledgeBase', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('Page.Home', 'Home/Index', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('EmployeeManagementSystem', 'Home/Index', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1),
    ('EmployeeManagementSystem.Description', 'Home/Index', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

INSERT INTO public."LanguageKeyForms"("Key", "FormName", "ApplicationUid", "DateCreated", "DateChanged", "BusinessEntityStatus")
VALUES 
    ('Notifications', 'Home/Notifications', 'd7b0eb60-190e-439d-89e1-c78594ac7f0c', now(), now(), 1);

-- A set of functions to simplify working with languages.

CREATE OR REPLACE FUNCTION "GetLanguageKvpByFormName"(aLanguageType int, aFormName varchar(100), aApplicationUid varchar(255))
RETURNS TABLE (
    "Id" bigint,
    "LanguageType" integer,
    "LanguageKeyId" bigint,
    "Key" text,
    "Value" text,
    "ApplicationUid" text,
    "DateCreated" timestamp with time zone,
    "DateChanged" timestamp with time zone,
    "BusinessEntityStatus" integer
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        lkvp."Id",
        lkvp."LanguageType",
        lkvp."LanguageKeyId",
        lkvp."Key",
        lkvp."Value",
        lkvp."ApplicationUid",
        lkvp."DateCreated",
        lkvp."DateChanged",
        lkvp."BusinessEntityStatus"
    FROM
        "LanguageKeyValuePairs" lkvp
    INNER JOIN
        "LanguageKeyForms" lkf ON lkvp."Key" = lkf."Key" AND lkvp."ApplicationUid" = lkf."ApplicationUid"
    WHERE
        lkvp."LanguageType" = aLanguageType
        AND lkf."FormName" = aFormName
        AND lkvp."ApplicationUid" = aApplicationUid;
END;
$$ LANGUAGE plpgsql;
